namaku = ("Centrino")
nim = ("2610817310015")
print ("##############################")
print ("#                            #")
print ("#         " + namaku + "           #")
print ("#       " + nim + "        #")
print ("#                            #")
print ("##############################")
